# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      # requires
      # nix-channel --add https://github.com/NixOS/nixos-hardware/archive/master.tar.gz nixos-hardware
      # before running install
      <nixos-hardware/raspberry-pi/4>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

#  fileSystems."/root" =
#    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
#      fsType = "btrfs";
#      options = [ "subvol=root-home" "compress=zstd" "noatime" ];
#    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C797-CAEA";
      fsType = "vfat";
    };

  #fileSystems."/tmp" = {
  #  fsType = "tmpfs";
  #  device = "tmpfs";
  #  options = ["nosuid" "nodev" "noatime" "size=8G"];
  #};

  fileSystems."/tmp" = {
    fsType = "btrfs";
    device = "/dev/disk/by-uuid/708b4e6f-2d05-4047-ac9f-5278adecc766";
    options = [ "subvol=tmptmp" "compress=zstd" "noatime" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/779091ff-584e-4bf4-8ee7-ee31668e83c3"; }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  hardware = {
    # high-resolution display
    video.hidpi.enable = lib.mkDefault true;
    enableRedistributableFirmware = true;
    raspberry-pi."4".fkms-3d.enable = true;
  };
}
