# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: let commonMountOptions = [
  "compress=zstd"
  "noatime"
  "ssd"
  "discard=async"
  "space_cache=1"
]; in

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  services.btrfs.autoScrub = {
    enable = true;
    fileSystems = [ "/" ];
    interval = "monthly";
  };

  fileSystems."/" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=@" ] ++ commonMountOptions;
    };

  fileSystems."/root" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=root" ] ++ commonMountOptions;
    };

  fileSystems."/home" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=home" ] ++ commonMountOptions;
    };

  fileSystems."/etc" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=etc" ] ++ commonMountOptions;
    };

  fileSystems."/var/db" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=db" ] ++ commonMountOptions;
    };

  fileSystems."/srv" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=srv" ] ++ commonMountOptions;
    };

  fileSystems."/opt" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=opt" ] ++ commonMountOptions;
    };

  fileSystems."/nix" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      options = [ "subvol=nix" ] ++ commonMountOptions;
    };

  fileSystems."/boot" =
    { device = "/dev/nvme0n1p2";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=boot" ] ++ commonMountOptions;
    };

  fileSystems."/boot/efi" =
    { device = "/dev/nvme0n1p1";
      fsType = "fat";
    };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
