# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/sda1";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/sda1";
      fsType = "btrfs";
      options = [ "subvol=home"  "compress=zstd" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/sda1";
      fsType = "btrfs";
      options = [ "subvol=nix"  "compress=zstd" "noatime"];
    };

  fileSystems."/var/log" =
    { device = "/dev/sda1";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=log"  "compress=zstd" "noatime"];
    };

  #fileSystems."/boot" =
  #  { device = "/dev/sda15";
  #    fsType = "vfat";
  #  };
  fileSystems."/boot" =
    { device = "/dev/sda1";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=boot" "noatime" ];
    };

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
