name: Update flake inputs
on:
  schedule:
    - cron: "54 6 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
    - name: update flake inputs
      run: nix flake update
    - name: Evaluate updated Linux and macOS configurations
      run: nix flake check --all-systems --no-build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        title: "chore: update flake inputs"
        commit-message: "chore: update flake inputs"
        delete-branch: true
        add-paths: flake.lock
